name: main
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ['v[0-9]*']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - run: make
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1
          config: examples/full/kind-config.yaml
      - run: make integration-test
      - if: failure()
        run: make -C examples/full dump-logs
