name: main
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ['v[0-9]*']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - run: go test -cover -v ./...
