name: main
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ['v[0-9]*']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - run: make
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/setup-kind@v0.5.0
      - run: make -C examples/full
      - run: make -C examples/full start-port-forwarding
      - run: make -C examples/full test
      - if: always()
        run: make -C examples/full dump-logs
      - if: always()
        run: make -C examples/full stop-port-forwarding
      - if: always()
        run: make -C examples/full delete
